version: '3.9'

services:
  # postgres
  postgres-db:
    container_name: postgres-tender
    image: postgres:latest
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
      POSTGRES_DB: tender
    volumes:
      - db:/post-database/post-memory
    ports:
      - "5434:5432"
    networks:
      - mynetwork
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6378:6379"
    volumes:
      - redis-data:/data
    networks:
      - mynetwork
  # tender-service
  tender-service:
    container_name: tender-service
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - postgres-db
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
    name: tender-network
    driver: bridge

volumes:
  db:
  redis-data:
    driver: local

